# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    image: viseo/spring-training-backend:0.0.1-SNAPSHOT
    container_name: spring-training-backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "25000:25000"

  frontend:
    build: ./frontend
    image: viseo/spring-training-frontend:0.0.1-SNAPSHOT
    container_name: spring-training-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"

  db:
    container_name: spring-training-postgres
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
