# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
